name: period_track
description: An application for tracking menusral cycle.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.10.0+33

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: "3.13.6"

dependencies:
  community_charts_flutter: ^1.0.1
  cloud_firestore: ^4.9.1
  crypto: ^3.0.3
  datetime_picker_formfield_new: ^2.1.0
  firebase_app_check: ^0.1.5+2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.4
  google_mobile_ads: ^3.0.0
  google_sign_in: ^6.1.5
  intl: ^0.18.0
  os_detect: ^2.0.1
  provider: ^6.0.5
  sign_in_with_apple: ^5.0.0
  sliding_up_panel: ^2.0.0+1
  table_calendar: ^3.0.9

dev_dependencies:
  arb_translator: ^1.0.5
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
  - images/logo.png
  - images/logo-alt.png
  - images/google-logo.png
  - images/flow-spotting.png
  - images/flow-light.png
  - images/flow-normal.png
  - images/flow-heavy.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" google_translate_key.txt with the font family name, and a "fonts" google_translate_key.txt with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
